// station/src/web/src/views/Settings.vue
<template>
    <div id="settings" class="flex-content">        
        <Loader v-if="loading"></Loader>
        <template v-else>
            <div class="flex-section">                
                <div class="flex-heading"><h2>WiFi Settings</h2><small>Connected to: {{connectedNetwork}}</small></div>
                <div class="form-line">
                    <label class="left-col" for="ssid">SSID</label>
                    <input class="right-col" v-model="ssid" length=32 />
                    <label class="left-col" for="pass">Pass</label>
                    <input class="right-col" v-model="pass" length=64 />
                </div>
                <button v-on:click="setWifiSettings()" class="button">Save WiFi Settings</button>
            </div>
        </template>
    </div>
</template>

<script lang="ts">
    import { Component, Vue } from "vue-property-decorator";
    import Loader from "../components/Loader.vue";

    @Component({
        components: {
            Loader
        },
    })
    export default class Settings extends Vue {
        private loading: boolean = true;
        private connectedNetwork: string = "NONE";

        private ssid : string = "";
        private pass : string = "";

        async beforeMount() {
            try {
                await this.getWifiSettings();
                this.loading = false;
            }
            catch(ex) {
                alert(ex);
            }            
        }

        async getWifiSettings() : Promise<void> {
            let response = await fetch("/api/wifi/get", {
                method: "GET"
            });
            if(response.ok) {
                let wifiInfo = await response.json();
                this.connectedNetwork = wifiInfo.connected ? wifiInfo.ssid : "NONE";
            }
            else { throw("Error during WiFi info request!"); }
        }

        async setWifiSettings() : Promise<void> {
            this.loading = true;
            let response = await fetch(`/api/wifi/set?ssid=${this.ssid}&pass=${this.pass}`, {
                method: "GET"
            });
            if(response.ok && (await response.json()).saved) {
                this.loading = false;
            }
            else { alert("Error saving WiFi settings!"); }
        }
    }
</script>

<style lang="scss">
    @import "./assets/sass/global.scss";
</style>

// station/src/web/src/components/mobile/Settings.tsx
import { useEffect, useState } from "react";
import styled from "styled-components";

import Button from "../ui/Button";
import Loader from "../ui/Loader";

function Settings() {
    const [showLoader, setShowLoader] = useState(true);
    const [scriptList, setScriptList] = useState<Array<string>>();

    const [script, setScript] = useState('');
    const [analyzer, setAnalyzer] = useState(0);

    useEffect(() => {
        (async () => {
            let listResponse = await fetch("/api/scripts/list");
            let meshResponse = await fetch("/api/mesh/info");
            let wifiResponse = await fetch("/api/wifi/get");
            if(listResponse.ok && meshResponse.ok && wifiResponse.ok) {
                let scriptList = (await listResponse.json()).scripts;
                let meshInfo = await meshResponse.json();
                let wifiInfo = await wifiResponse.json();

                setScriptList(scriptList);
                setScript(meshInfo.script);
                setAnalyzer(meshInfo.analyzer);
            }
            else { throw new Error("Error during requests!"); }
            setShowLoader(false);
        })();
    }, []);

    return <StyledSettings>
        { showLoader && <Loader message="Loading..." transparent={false}></Loader> }
        <h2>Script Settings</h2>
        <div className="settings">
            <div className="form-line">
                <label>Active Script</label>
                <select></select>
            </div>
            <div className="form-line">
                <label>Analyzer</label>
                <select></select>
            </div>
        </div>
        <Button>Save</Button>
        <h2>WiFi Settings</h2>
        <div className="settings">
            <div className="form-line">
                <label htmlFor="ssid">SSID</label><input v-model="ssid" maxLength={32} />
            </div>
            <div className="form-line">
                <label htmlFor="pass">Pass</label><input v-model="pass" maxLength={64} />
            </div>
        </div>
        <Button>Save</Button>
    </StyledSettings>;
}

const StyledSettings = styled.div`
    height: 100vh;
    padding: 20px;

    .form-line {
        margin-bottom: 0.75rem;
        display: grid;
        grid-template-areas: "left right";
        grid-template-columns: 100px 1fr;

        label { text-align: right; }
        input, select { margin-left: 0.75rem; padding: 5px; color: $text-color; }
    }


    button {
        margin-bottom: 20px;
    }
`;

export default Settings;
